name: Build Docker with Tests

on: push

jobs:
  test:
    strategy:
        matrix:
          image:
              - name: python3.12
                python_version: "3.12"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.12'

      - name: Install Dependences
        run: |
            python -m pip install --upgrade pip 
            pip install -r docker-images/requirements.txt
            pip install pytest
            pip install docker
      - name: Docker names
        run: echo "NAME=${{ mathix.image.name  }}" >> $GITHUB_ENV 
      - name: Run Tests
        run: pytest tests
        env:
            NAME: ${{ matrix.image.name  }}
            PYTHON_VERSION: ${{ matrix.image.python_version }}

  build:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Log in GHCR
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}


